/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.ColdChip.GrowtopiaServer.ENetJava;

public class ENetProtocolVerifyConnect {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetProtocolVerifyConnect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetProtocolVerifyConnect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetProtocolVerifyConnect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeader(ENetProtocolCommandHeader value) {
    enetJNI.ENetProtocolVerifyConnect_header_set(swigCPtr, this, ENetProtocolCommandHeader.getCPtr(value), value);
  }

  public ENetProtocolCommandHeader getHeader() {
    long cPtr = enetJNI.ENetProtocolVerifyConnect_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolCommandHeader(cPtr, false);
  }

  public void setOutgoingPeerID(int value) {
    enetJNI.ENetProtocolVerifyConnect_outgoingPeerID_set(swigCPtr, this, value);
  }

  public int getOutgoingPeerID() {
    return enetJNI.ENetProtocolVerifyConnect_outgoingPeerID_get(swigCPtr, this);
  }

  public void setIncomingSessionID(short value) {
    enetJNI.ENetProtocolVerifyConnect_incomingSessionID_set(swigCPtr, this, value);
  }

  public short getIncomingSessionID() {
    return enetJNI.ENetProtocolVerifyConnect_incomingSessionID_get(swigCPtr, this);
  }

  public void setOutgoingSessionID(short value) {
    enetJNI.ENetProtocolVerifyConnect_outgoingSessionID_set(swigCPtr, this, value);
  }

  public short getOutgoingSessionID() {
    return enetJNI.ENetProtocolVerifyConnect_outgoingSessionID_get(swigCPtr, this);
  }

  public void setMtu(long value) {
    enetJNI.ENetProtocolVerifyConnect_mtu_set(swigCPtr, this, value);
  }

  public long getMtu() {
    return enetJNI.ENetProtocolVerifyConnect_mtu_get(swigCPtr, this);
  }

  public void setWindowSize(long value) {
    enetJNI.ENetProtocolVerifyConnect_windowSize_set(swigCPtr, this, value);
  }

  public long getWindowSize() {
    return enetJNI.ENetProtocolVerifyConnect_windowSize_get(swigCPtr, this);
  }

  public void setChannelCount(long value) {
    enetJNI.ENetProtocolVerifyConnect_channelCount_set(swigCPtr, this, value);
  }

  public long getChannelCount() {
    return enetJNI.ENetProtocolVerifyConnect_channelCount_get(swigCPtr, this);
  }

  public void setIncomingBandwidth(long value) {
    enetJNI.ENetProtocolVerifyConnect_incomingBandwidth_set(swigCPtr, this, value);
  }

  public long getIncomingBandwidth() {
    return enetJNI.ENetProtocolVerifyConnect_incomingBandwidth_get(swigCPtr, this);
  }

  public void setOutgoingBandwidth(long value) {
    enetJNI.ENetProtocolVerifyConnect_outgoingBandwidth_set(swigCPtr, this, value);
  }

  public long getOutgoingBandwidth() {
    return enetJNI.ENetProtocolVerifyConnect_outgoingBandwidth_get(swigCPtr, this);
  }

  public void setPacketThrottleInterval(long value) {
    enetJNI.ENetProtocolVerifyConnect_packetThrottleInterval_set(swigCPtr, this, value);
  }

  public long getPacketThrottleInterval() {
    return enetJNI.ENetProtocolVerifyConnect_packetThrottleInterval_get(swigCPtr, this);
  }

  public void setPacketThrottleAcceleration(long value) {
    enetJNI.ENetProtocolVerifyConnect_packetThrottleAcceleration_set(swigCPtr, this, value);
  }

  public long getPacketThrottleAcceleration() {
    return enetJNI.ENetProtocolVerifyConnect_packetThrottleAcceleration_get(swigCPtr, this);
  }

  public void setPacketThrottleDeceleration(long value) {
    enetJNI.ENetProtocolVerifyConnect_packetThrottleDeceleration_set(swigCPtr, this, value);
  }

  public long getPacketThrottleDeceleration() {
    return enetJNI.ENetProtocolVerifyConnect_packetThrottleDeceleration_get(swigCPtr, this);
  }

  public void setConnectID(long value) {
    enetJNI.ENetProtocolVerifyConnect_connectID_set(swigCPtr, this, value);
  }

  public long getConnectID() {
    return enetJNI.ENetProtocolVerifyConnect_connectID_get(swigCPtr, this);
  }

  public ENetProtocolVerifyConnect() {
    this(enetJNI.new_ENetProtocolVerifyConnect(), true);
  }

}
