/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.ColdChip.GrowtopiaServer.ENetJava;

public class ENetProtocolThrottleConfigure {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetProtocolThrottleConfigure(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetProtocolThrottleConfigure obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetProtocolThrottleConfigure(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeader(ENetProtocolCommandHeader value) {
    enetJNI.ENetProtocolThrottleConfigure_header_set(swigCPtr, this, ENetProtocolCommandHeader.getCPtr(value), value);
  }

  public ENetProtocolCommandHeader getHeader() {
    long cPtr = enetJNI.ENetProtocolThrottleConfigure_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolCommandHeader(cPtr, false);
  }

  public void setPacketThrottleInterval(long value) {
    enetJNI.ENetProtocolThrottleConfigure_packetThrottleInterval_set(swigCPtr, this, value);
  }

  public long getPacketThrottleInterval() {
    return enetJNI.ENetProtocolThrottleConfigure_packetThrottleInterval_get(swigCPtr, this);
  }

  public void setPacketThrottleAcceleration(long value) {
    enetJNI.ENetProtocolThrottleConfigure_packetThrottleAcceleration_set(swigCPtr, this, value);
  }

  public long getPacketThrottleAcceleration() {
    return enetJNI.ENetProtocolThrottleConfigure_packetThrottleAcceleration_get(swigCPtr, this);
  }

  public void setPacketThrottleDeceleration(long value) {
    enetJNI.ENetProtocolThrottleConfigure_packetThrottleDeceleration_set(swigCPtr, this, value);
  }

  public long getPacketThrottleDeceleration() {
    return enetJNI.ENetProtocolThrottleConfigure_packetThrottleDeceleration_get(swigCPtr, this);
  }

  public ENetProtocolThrottleConfigure() {
    this(enetJNI.new_ENetProtocolThrottleConfigure(), true);
  }

}
