/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.ColdChip.GrowtopiaServer.ENetJava;

public class ENetProtocolSendFragment {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetProtocolSendFragment(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetProtocolSendFragment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetProtocolSendFragment(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeader(ENetProtocolCommandHeader value) {
    enetJNI.ENetProtocolSendFragment_header_set(swigCPtr, this, ENetProtocolCommandHeader.getCPtr(value), value);
  }

  public ENetProtocolCommandHeader getHeader() {
    long cPtr = enetJNI.ENetProtocolSendFragment_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolCommandHeader(cPtr, false);
  }

  public void setStartSequenceNumber(int value) {
    enetJNI.ENetProtocolSendFragment_startSequenceNumber_set(swigCPtr, this, value);
  }

  public int getStartSequenceNumber() {
    return enetJNI.ENetProtocolSendFragment_startSequenceNumber_get(swigCPtr, this);
  }

  public void setDataLength(int value) {
    enetJNI.ENetProtocolSendFragment_dataLength_set(swigCPtr, this, value);
  }

  public int getDataLength() {
    return enetJNI.ENetProtocolSendFragment_dataLength_get(swigCPtr, this);
  }

  public void setFragmentCount(long value) {
    enetJNI.ENetProtocolSendFragment_fragmentCount_set(swigCPtr, this, value);
  }

  public long getFragmentCount() {
    return enetJNI.ENetProtocolSendFragment_fragmentCount_get(swigCPtr, this);
  }

  public void setFragmentNumber(long value) {
    enetJNI.ENetProtocolSendFragment_fragmentNumber_set(swigCPtr, this, value);
  }

  public long getFragmentNumber() {
    return enetJNI.ENetProtocolSendFragment_fragmentNumber_get(swigCPtr, this);
  }

  public void setTotalLength(long value) {
    enetJNI.ENetProtocolSendFragment_totalLength_set(swigCPtr, this, value);
  }

  public long getTotalLength() {
    return enetJNI.ENetProtocolSendFragment_totalLength_get(swigCPtr, this);
  }

  public void setFragmentOffset(long value) {
    enetJNI.ENetProtocolSendFragment_fragmentOffset_set(swigCPtr, this, value);
  }

  public long getFragmentOffset() {
    return enetJNI.ENetProtocolSendFragment_fragmentOffset_get(swigCPtr, this);
  }

  public ENetProtocolSendFragment() {
    this(enetJNI.new_ENetProtocolSendFragment(), true);
  }

}
