/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.ColdChip.GrowtopiaServer.ENetJava;

public class ENetList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSentinel(ENetListNode value) {
    enetJNI.ENetList_sentinel_set(swigCPtr, this, ENetListNode.getCPtr(value), value);
  }

  public ENetListNode getSentinel() {
    long cPtr = enetJNI.ENetList_sentinel_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetListNode(cPtr, false);
  }

  public ENetList() {
    this(enetJNI.new_ENetList(), true);
  }

}
