/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.ColdChip.GrowtopiaServer.ENetJava;

public class ENetProtocolCommandHeader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetProtocolCommandHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetProtocolCommandHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetProtocolCommandHeader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCommand(short value) {
    enetJNI.ENetProtocolCommandHeader_command_set(swigCPtr, this, value);
  }

  public short getCommand() {
    return enetJNI.ENetProtocolCommandHeader_command_get(swigCPtr, this);
  }

  public void setChannelID(short value) {
    enetJNI.ENetProtocolCommandHeader_channelID_set(swigCPtr, this, value);
  }

  public short getChannelID() {
    return enetJNI.ENetProtocolCommandHeader_channelID_get(swigCPtr, this);
  }

  public void setReliableSequenceNumber(int value) {
    enetJNI.ENetProtocolCommandHeader_reliableSequenceNumber_set(swigCPtr, this, value);
  }

  public int getReliableSequenceNumber() {
    return enetJNI.ENetProtocolCommandHeader_reliableSequenceNumber_get(swigCPtr, this);
  }

  public ENetProtocolCommandHeader() {
    this(enetJNI.new_ENetProtocolCommandHeader(), true);
  }

}
