/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ENet;

public class ENetAcknowledgement {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetAcknowledgement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetAcknowledgement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetAcknowledgement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAcknowledgementList(ENetListNode value) {
    enetJNI.ENetAcknowledgement_acknowledgementList_set(swigCPtr, this, ENetListNode.getCPtr(value), value);
  }

  public ENetListNode getAcknowledgementList() {
    long cPtr = enetJNI.ENetAcknowledgement_acknowledgementList_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetListNode(cPtr, false);
  }

  public void setSentTime(long value) {
    enetJNI.ENetAcknowledgement_sentTime_set(swigCPtr, this, value);
  }

  public long getSentTime() {
    return enetJNI.ENetAcknowledgement_sentTime_get(swigCPtr, this);
  }

  public void setCommand(ENetProtocol value) {
    enetJNI.ENetAcknowledgement_command_set(swigCPtr, this, ENetProtocol.getCPtr(value), value);
  }

  public ENetProtocol getCommand() {
    long cPtr = enetJNI.ENetAcknowledgement_command_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocol(cPtr, false);
  }

  public ENetAcknowledgement() {
    this(enetJNI.new_ENetAcknowledgement(), true);
  }

}
