/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ENet;

public final class ENetProtocolCommand {
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_NONE = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_NONE", enetJNI.ENET_PROTOCOL_COMMAND_NONE_get());
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_ACKNOWLEDGE = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_ACKNOWLEDGE", enetJNI.ENET_PROTOCOL_COMMAND_ACKNOWLEDGE_get());
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_CONNECT = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_CONNECT", enetJNI.ENET_PROTOCOL_COMMAND_CONNECT_get());
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_VERIFY_CONNECT = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_VERIFY_CONNECT", enetJNI.ENET_PROTOCOL_COMMAND_VERIFY_CONNECT_get());
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_DISCONNECT = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_DISCONNECT", enetJNI.ENET_PROTOCOL_COMMAND_DISCONNECT_get());
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_PING = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_PING", enetJNI.ENET_PROTOCOL_COMMAND_PING_get());
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_SEND_RELIABLE = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_SEND_RELIABLE", enetJNI.ENET_PROTOCOL_COMMAND_SEND_RELIABLE_get());
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_SEND_UNRELIABLE = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_SEND_UNRELIABLE", enetJNI.ENET_PROTOCOL_COMMAND_SEND_UNRELIABLE_get());
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_SEND_FRAGMENT = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_SEND_FRAGMENT", enetJNI.ENET_PROTOCOL_COMMAND_SEND_FRAGMENT_get());
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_SEND_UNSEQUENCED = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_SEND_UNSEQUENCED", enetJNI.ENET_PROTOCOL_COMMAND_SEND_UNSEQUENCED_get());
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_BANDWIDTH_LIMIT = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_BANDWIDTH_LIMIT", enetJNI.ENET_PROTOCOL_COMMAND_BANDWIDTH_LIMIT_get());
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_THROTTLE_CONFIGURE = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_THROTTLE_CONFIGURE", enetJNI.ENET_PROTOCOL_COMMAND_THROTTLE_CONFIGURE_get());
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_SEND_UNRELIABLE_FRAGMENT = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_SEND_UNRELIABLE_FRAGMENT", enetJNI.ENET_PROTOCOL_COMMAND_SEND_UNRELIABLE_FRAGMENT_get());
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_COUNT = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_COUNT", enetJNI.ENET_PROTOCOL_COMMAND_COUNT_get());
  public final static ENetProtocolCommand ENET_PROTOCOL_COMMAND_MASK = new ENetProtocolCommand("ENET_PROTOCOL_COMMAND_MASK", enetJNI.ENET_PROTOCOL_COMMAND_MASK_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ENetProtocolCommand swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ENetProtocolCommand.class + " with value " + swigValue);
  }

  private ENetProtocolCommand(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ENetProtocolCommand(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ENetProtocolCommand(String swigName, ENetProtocolCommand swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ENetProtocolCommand[] swigValues = { ENET_PROTOCOL_COMMAND_NONE, ENET_PROTOCOL_COMMAND_ACKNOWLEDGE, ENET_PROTOCOL_COMMAND_CONNECT, ENET_PROTOCOL_COMMAND_VERIFY_CONNECT, ENET_PROTOCOL_COMMAND_DISCONNECT, ENET_PROTOCOL_COMMAND_PING, ENET_PROTOCOL_COMMAND_SEND_RELIABLE, ENET_PROTOCOL_COMMAND_SEND_UNRELIABLE, ENET_PROTOCOL_COMMAND_SEND_FRAGMENT, ENET_PROTOCOL_COMMAND_SEND_UNSEQUENCED, ENET_PROTOCOL_COMMAND_BANDWIDTH_LIMIT, ENET_PROTOCOL_COMMAND_THROTTLE_CONFIGURE, ENET_PROTOCOL_COMMAND_SEND_UNRELIABLE_FRAGMENT, ENET_PROTOCOL_COMMAND_COUNT, ENET_PROTOCOL_COMMAND_MASK };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

