/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ENet;

public class ENetChannel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetChannel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetChannel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetChannel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOutgoingReliableSequenceNumber(int value) {
    enetJNI.ENetChannel_outgoingReliableSequenceNumber_set(swigCPtr, this, value);
  }

  public int getOutgoingReliableSequenceNumber() {
    return enetJNI.ENetChannel_outgoingReliableSequenceNumber_get(swigCPtr, this);
  }

  public void setOutgoingUnreliableSequenceNumber(int value) {
    enetJNI.ENetChannel_outgoingUnreliableSequenceNumber_set(swigCPtr, this, value);
  }

  public int getOutgoingUnreliableSequenceNumber() {
    return enetJNI.ENetChannel_outgoingUnreliableSequenceNumber_get(swigCPtr, this);
  }

  public void setUsedReliableWindows(int value) {
    enetJNI.ENetChannel_usedReliableWindows_set(swigCPtr, this, value);
  }

  public int getUsedReliableWindows() {
    return enetJNI.ENetChannel_usedReliableWindows_get(swigCPtr, this);
  }

  public void setReliableWindows(SWIGTYPE_p_unsigned_short value) {
    enetJNI.ENetChannel_reliableWindows_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getReliableWindows() {
    long cPtr = enetJNI.ENetChannel_reliableWindows_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setIncomingReliableSequenceNumber(int value) {
    enetJNI.ENetChannel_incomingReliableSequenceNumber_set(swigCPtr, this, value);
  }

  public int getIncomingReliableSequenceNumber() {
    return enetJNI.ENetChannel_incomingReliableSequenceNumber_get(swigCPtr, this);
  }

  public void setIncomingUnreliableSequenceNumber(int value) {
    enetJNI.ENetChannel_incomingUnreliableSequenceNumber_set(swigCPtr, this, value);
  }

  public int getIncomingUnreliableSequenceNumber() {
    return enetJNI.ENetChannel_incomingUnreliableSequenceNumber_get(swigCPtr, this);
  }

  public void setIncomingReliableCommands(ENetList value) {
    enetJNI.ENetChannel_incomingReliableCommands_set(swigCPtr, this, ENetList.getCPtr(value), value);
  }

  public ENetList getIncomingReliableCommands() {
    long cPtr = enetJNI.ENetChannel_incomingReliableCommands_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetList(cPtr, false);
  }

  public void setIncomingUnreliableCommands(ENetList value) {
    enetJNI.ENetChannel_incomingUnreliableCommands_set(swigCPtr, this, ENetList.getCPtr(value), value);
  }

  public ENetList getIncomingUnreliableCommands() {
    long cPtr = enetJNI.ENetChannel_incomingUnreliableCommands_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetList(cPtr, false);
  }

  public ENetChannel() {
    this(enetJNI.new_ENetChannel(), true);
  }

}
