/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Enet;

public class ENetCallbacks {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetCallbacks(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetCallbacks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetCallbacks(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMalloc(SWIGTYPE_p_f_size_t__p_void value) {
    enetJNI.ENetCallbacks_malloc_set(swigCPtr, this, SWIGTYPE_p_f_size_t__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_size_t__p_void getMalloc() {
    long cPtr = enetJNI.ENetCallbacks_malloc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_size_t__p_void(cPtr, false);
  }

  public void setFree(SWIGTYPE_p_f_p_void__void value) {
    enetJNI.ENetCallbacks_free_set(swigCPtr, this, SWIGTYPE_p_f_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void__void getFree() {
    long cPtr = enetJNI.ENetCallbacks_free_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
  }

  public void setNo_memory(SWIGTYPE_p_f_void__void value) {
    enetJNI.ENetCallbacks_no_memory_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void getNo_memory() {
    long cPtr = enetJNI.ENetCallbacks_no_memory_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public ENetCallbacks() {
    this(enetJNI.new_ENetCallbacks(), true);
  }

}
