/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ENet;

public class ENetProtocolConnect {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetProtocolConnect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetProtocolConnect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetProtocolConnect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeader(ENetProtocolCommandHeader value) {
    enetJNI.ENetProtocolConnect_header_set(swigCPtr, this, ENetProtocolCommandHeader.getCPtr(value), value);
  }

  public ENetProtocolCommandHeader getHeader() {
    long cPtr = enetJNI.ENetProtocolConnect_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolCommandHeader(cPtr, false);
  }

  public void setOutgoingPeerID(int value) {
    enetJNI.ENetProtocolConnect_outgoingPeerID_set(swigCPtr, this, value);
  }

  public int getOutgoingPeerID() {
    return enetJNI.ENetProtocolConnect_outgoingPeerID_get(swigCPtr, this);
  }

  public void setIncomingSessionID(short value) {
    enetJNI.ENetProtocolConnect_incomingSessionID_set(swigCPtr, this, value);
  }

  public short getIncomingSessionID() {
    return enetJNI.ENetProtocolConnect_incomingSessionID_get(swigCPtr, this);
  }

  public void setOutgoingSessionID(short value) {
    enetJNI.ENetProtocolConnect_outgoingSessionID_set(swigCPtr, this, value);
  }

  public short getOutgoingSessionID() {
    return enetJNI.ENetProtocolConnect_outgoingSessionID_get(swigCPtr, this);
  }

  public void setMtu(long value) {
    enetJNI.ENetProtocolConnect_mtu_set(swigCPtr, this, value);
  }

  public long getMtu() {
    return enetJNI.ENetProtocolConnect_mtu_get(swigCPtr, this);
  }

  public void setWindowSize(long value) {
    enetJNI.ENetProtocolConnect_windowSize_set(swigCPtr, this, value);
  }

  public long getWindowSize() {
    return enetJNI.ENetProtocolConnect_windowSize_get(swigCPtr, this);
  }

  public void setChannelCount(long value) {
    enetJNI.ENetProtocolConnect_channelCount_set(swigCPtr, this, value);
  }

  public long getChannelCount() {
    return enetJNI.ENetProtocolConnect_channelCount_get(swigCPtr, this);
  }

  public void setIncomingBandwidth(long value) {
    enetJNI.ENetProtocolConnect_incomingBandwidth_set(swigCPtr, this, value);
  }

  public long getIncomingBandwidth() {
    return enetJNI.ENetProtocolConnect_incomingBandwidth_get(swigCPtr, this);
  }

  public void setOutgoingBandwidth(long value) {
    enetJNI.ENetProtocolConnect_outgoingBandwidth_set(swigCPtr, this, value);
  }

  public long getOutgoingBandwidth() {
    return enetJNI.ENetProtocolConnect_outgoingBandwidth_get(swigCPtr, this);
  }

  public void setPacketThrottleInterval(long value) {
    enetJNI.ENetProtocolConnect_packetThrottleInterval_set(swigCPtr, this, value);
  }

  public long getPacketThrottleInterval() {
    return enetJNI.ENetProtocolConnect_packetThrottleInterval_get(swigCPtr, this);
  }

  public void setPacketThrottleAcceleration(long value) {
    enetJNI.ENetProtocolConnect_packetThrottleAcceleration_set(swigCPtr, this, value);
  }

  public long getPacketThrottleAcceleration() {
    return enetJNI.ENetProtocolConnect_packetThrottleAcceleration_get(swigCPtr, this);
  }

  public void setPacketThrottleDeceleration(long value) {
    enetJNI.ENetProtocolConnect_packetThrottleDeceleration_set(swigCPtr, this, value);
  }

  public long getPacketThrottleDeceleration() {
    return enetJNI.ENetProtocolConnect_packetThrottleDeceleration_get(swigCPtr, this);
  }

  public void setConnectID(long value) {
    enetJNI.ENetProtocolConnect_connectID_set(swigCPtr, this, value);
  }

  public long getConnectID() {
    return enetJNI.ENetProtocolConnect_connectID_get(swigCPtr, this);
  }

  public void setData(long value) {
    enetJNI.ENetProtocolConnect_data_set(swigCPtr, this, value);
  }

  public long getData() {
    return enetJNI.ENetProtocolConnect_data_get(swigCPtr, this);
  }

  public ENetProtocolConnect() {
    this(enetJNI.new_ENetProtocolConnect(), true);
  }

}
