/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Enet;

public class ENetProtocolSendUnsequenced {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetProtocolSendUnsequenced(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetProtocolSendUnsequenced obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetProtocolSendUnsequenced(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeader(ENetProtocolCommandHeader value) {
    enetJNI.ENetProtocolSendUnsequenced_header_set(swigCPtr, this, ENetProtocolCommandHeader.getCPtr(value), value);
  }

  public ENetProtocolCommandHeader getHeader() {
    long cPtr = enetJNI.ENetProtocolSendUnsequenced_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolCommandHeader(cPtr, false);
  }

  public void setUnsequencedGroup(int value) {
    enetJNI.ENetProtocolSendUnsequenced_unsequencedGroup_set(swigCPtr, this, value);
  }

  public int getUnsequencedGroup() {
    return enetJNI.ENetProtocolSendUnsequenced_unsequencedGroup_get(swigCPtr, this);
  }

  public void setDataLength(int value) {
    enetJNI.ENetProtocolSendUnsequenced_dataLength_set(swigCPtr, this, value);
  }

  public int getDataLength() {
    return enetJNI.ENetProtocolSendUnsequenced_dataLength_get(swigCPtr, this);
  }

  public ENetProtocolSendUnsequenced() {
    this(enetJNI.new_ENetProtocolSendUnsequenced(), true);
  }

}
