/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Enet;

public class ENetProtocolBandwidthLimit {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetProtocolBandwidthLimit(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetProtocolBandwidthLimit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetProtocolBandwidthLimit(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeader(ENetProtocolCommandHeader value) {
    enetJNI.ENetProtocolBandwidthLimit_header_set(swigCPtr, this, ENetProtocolCommandHeader.getCPtr(value), value);
  }

  public ENetProtocolCommandHeader getHeader() {
    long cPtr = enetJNI.ENetProtocolBandwidthLimit_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolCommandHeader(cPtr, false);
  }

  public void setIncomingBandwidth(long value) {
    enetJNI.ENetProtocolBandwidthLimit_incomingBandwidth_set(swigCPtr, this, value);
  }

  public long getIncomingBandwidth() {
    return enetJNI.ENetProtocolBandwidthLimit_incomingBandwidth_get(swigCPtr, this);
  }

  public void setOutgoingBandwidth(long value) {
    enetJNI.ENetProtocolBandwidthLimit_outgoingBandwidth_set(swigCPtr, this, value);
  }

  public long getOutgoingBandwidth() {
    return enetJNI.ENetProtocolBandwidthLimit_outgoingBandwidth_get(swigCPtr, this);
  }

  public ENetProtocolBandwidthLimit() {
    this(enetJNI.new_ENetProtocolBandwidthLimit(), true);
  }

}
