/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ENet;

public class ENetAddress {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetAddress(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetAddress obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetAddress(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHost(long value) {
    enetJNI.ENetAddress_host_set(swigCPtr, this, value);
  }

  public long getHost() {
    return enetJNI.ENetAddress_host_get(swigCPtr, this);
  }

  public void setPort(int value) {
    enetJNI.ENetAddress_port_set(swigCPtr, this, value);
  }

  public int getPort() {
    return enetJNI.ENetAddress_port_get(swigCPtr, this);
  }

  public ENetAddress() {
    this(enetJNI.new_ENetAddress(), true);
  }

}
