/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ENet;

public class ENetProtocolPing {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetProtocolPing(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetProtocolPing obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetProtocolPing(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeader(ENetProtocolCommandHeader value) {
    enetJNI.ENetProtocolPing_header_set(swigCPtr, this, ENetProtocolCommandHeader.getCPtr(value), value);
  }

  public ENetProtocolCommandHeader getHeader() {
    long cPtr = enetJNI.ENetProtocolPing_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolCommandHeader(cPtr, false);
  }

  public ENetProtocolPing() {
    this(enetJNI.new_ENetProtocolPing(), true);
  }

}
