/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Enet;

public class ENetProtocol {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetProtocol(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetProtocol obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetProtocol(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeader(ENetProtocolCommandHeader value) {
    enetJNI.ENetProtocol_header_set(swigCPtr, this, ENetProtocolCommandHeader.getCPtr(value), value);
  }

  public ENetProtocolCommandHeader getHeader() {
    long cPtr = enetJNI.ENetProtocol_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolCommandHeader(cPtr, false);
  }

  public void setAcknowledge(ENetProtocolAcknowledge value) {
    enetJNI.ENetProtocol_acknowledge_set(swigCPtr, this, ENetProtocolAcknowledge.getCPtr(value), value);
  }

  public ENetProtocolAcknowledge getAcknowledge() {
    long cPtr = enetJNI.ENetProtocol_acknowledge_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolAcknowledge(cPtr, false);
  }

  public void setConnect(ENetProtocolConnect value) {
    enetJNI.ENetProtocol_connect_set(swigCPtr, this, ENetProtocolConnect.getCPtr(value), value);
  }

  public ENetProtocolConnect getConnect() {
    long cPtr = enetJNI.ENetProtocol_connect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolConnect(cPtr, false);
  }

  public void setVerifyConnect(ENetProtocolVerifyConnect value) {
    enetJNI.ENetProtocol_verifyConnect_set(swigCPtr, this, ENetProtocolVerifyConnect.getCPtr(value), value);
  }

  public ENetProtocolVerifyConnect getVerifyConnect() {
    long cPtr = enetJNI.ENetProtocol_verifyConnect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolVerifyConnect(cPtr, false);
  }

  public void setDisconnect(ENetProtocolDisconnect value) {
    enetJNI.ENetProtocol_disconnect_set(swigCPtr, this, ENetProtocolDisconnect.getCPtr(value), value);
  }

  public ENetProtocolDisconnect getDisconnect() {
    long cPtr = enetJNI.ENetProtocol_disconnect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolDisconnect(cPtr, false);
  }

  public void setPing(ENetProtocolPing value) {
    enetJNI.ENetProtocol_ping_set(swigCPtr, this, ENetProtocolPing.getCPtr(value), value);
  }

  public ENetProtocolPing getPing() {
    long cPtr = enetJNI.ENetProtocol_ping_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolPing(cPtr, false);
  }

  public void setSendReliable(ENetProtocolSendReliable value) {
    enetJNI.ENetProtocol_sendReliable_set(swigCPtr, this, ENetProtocolSendReliable.getCPtr(value), value);
  }

  public ENetProtocolSendReliable getSendReliable() {
    long cPtr = enetJNI.ENetProtocol_sendReliable_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolSendReliable(cPtr, false);
  }

  public void setSendUnreliable(ENetProtocolSendUnreliable value) {
    enetJNI.ENetProtocol_sendUnreliable_set(swigCPtr, this, ENetProtocolSendUnreliable.getCPtr(value), value);
  }

  public ENetProtocolSendUnreliable getSendUnreliable() {
    long cPtr = enetJNI.ENetProtocol_sendUnreliable_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolSendUnreliable(cPtr, false);
  }

  public void setSendUnsequenced(ENetProtocolSendUnsequenced value) {
    enetJNI.ENetProtocol_sendUnsequenced_set(swigCPtr, this, ENetProtocolSendUnsequenced.getCPtr(value), value);
  }

  public ENetProtocolSendUnsequenced getSendUnsequenced() {
    long cPtr = enetJNI.ENetProtocol_sendUnsequenced_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolSendUnsequenced(cPtr, false);
  }

  public void setSendFragment(ENetProtocolSendFragment value) {
    enetJNI.ENetProtocol_sendFragment_set(swigCPtr, this, ENetProtocolSendFragment.getCPtr(value), value);
  }

  public ENetProtocolSendFragment getSendFragment() {
    long cPtr = enetJNI.ENetProtocol_sendFragment_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolSendFragment(cPtr, false);
  }

  public void setBandwidthLimit(ENetProtocolBandwidthLimit value) {
    enetJNI.ENetProtocol_bandwidthLimit_set(swigCPtr, this, ENetProtocolBandwidthLimit.getCPtr(value), value);
  }

  public ENetProtocolBandwidthLimit getBandwidthLimit() {
    long cPtr = enetJNI.ENetProtocol_bandwidthLimit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolBandwidthLimit(cPtr, false);
  }

  public void setThrottleConfigure(ENetProtocolThrottleConfigure value) {
    enetJNI.ENetProtocol_throttleConfigure_set(swigCPtr, this, ENetProtocolThrottleConfigure.getCPtr(value), value);
  }

  public ENetProtocolThrottleConfigure getThrottleConfigure() {
    long cPtr = enetJNI.ENetProtocol_throttleConfigure_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolThrottleConfigure(cPtr, false);
  }

  public ENetProtocol() {
    this(enetJNI.new_ENetProtocol(), true);
  }

}
