/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ENetJava;

public interface enetConstants {
  public final static int ENET_SOCKET_NULL = enetJNI.ENET_SOCKET_NULL_get();
  public final static int ENET_PROTOCOL_MINIMUM_MTU = enetJNI.ENET_PROTOCOL_MINIMUM_MTU_get();
  public final static int ENET_PROTOCOL_MAXIMUM_MTU = enetJNI.ENET_PROTOCOL_MAXIMUM_MTU_get();
  public final static int ENET_PROTOCOL_MAXIMUM_PACKET_COMMANDS = enetJNI.ENET_PROTOCOL_MAXIMUM_PACKET_COMMANDS_get();
  public final static int ENET_PROTOCOL_MINIMUM_WINDOW_SIZE = enetJNI.ENET_PROTOCOL_MINIMUM_WINDOW_SIZE_get();
  public final static int ENET_PROTOCOL_MAXIMUM_WINDOW_SIZE = enetJNI.ENET_PROTOCOL_MAXIMUM_WINDOW_SIZE_get();
  public final static int ENET_PROTOCOL_MINIMUM_CHANNEL_COUNT = enetJNI.ENET_PROTOCOL_MINIMUM_CHANNEL_COUNT_get();
  public final static int ENET_PROTOCOL_MAXIMUM_CHANNEL_COUNT = enetJNI.ENET_PROTOCOL_MAXIMUM_CHANNEL_COUNT_get();
  public final static int ENET_PROTOCOL_MAXIMUM_PEER_ID = enetJNI.ENET_PROTOCOL_MAXIMUM_PEER_ID_get();
  public final static int ENET_PROTOCOL_MAXIMUM_FRAGMENT_COUNT = enetJNI.ENET_PROTOCOL_MAXIMUM_FRAGMENT_COUNT_get();

  public final static int ENET_VERSION_MAJOR = enetJNI.ENET_VERSION_MAJOR_get();
  public final static int ENET_VERSION_MINOR = enetJNI.ENET_VERSION_MINOR_get();
  public final static int ENET_VERSION_PATCH = enetJNI.ENET_VERSION_PATCH_get();
  public final static int ENET_VERSION = enetJNI.ENET_VERSION_get();
  public final static int ENET_HOST_ANY = enetJNI.ENET_HOST_ANY_get();
  public final static long ENET_HOST_BROADCAST = enetJNI.ENET_HOST_BROADCAST_get();
  public final static int ENET_PORT_ANY = enetJNI.ENET_PORT_ANY_get();
  public final static int ENET_HOST_RECEIVE_BUFFER_SIZE = enetJNI.ENET_HOST_RECEIVE_BUFFER_SIZE_get();
  public final static int ENET_HOST_SEND_BUFFER_SIZE = enetJNI.ENET_HOST_SEND_BUFFER_SIZE_get();
  public final static int ENET_HOST_BANDWIDTH_THROTTLE_INTERVAL = enetJNI.ENET_HOST_BANDWIDTH_THROTTLE_INTERVAL_get();
  public final static int ENET_HOST_DEFAULT_MTU = enetJNI.ENET_HOST_DEFAULT_MTU_get();
  public final static int ENET_HOST_DEFAULT_MAXIMUM_PACKET_SIZE = enetJNI.ENET_HOST_DEFAULT_MAXIMUM_PACKET_SIZE_get();
  public final static int ENET_HOST_DEFAULT_MAXIMUM_WAITING_DATA = enetJNI.ENET_HOST_DEFAULT_MAXIMUM_WAITING_DATA_get();
  public final static int ENET_PEER_DEFAULT_ROUND_TRIP_TIME = enetJNI.ENET_PEER_DEFAULT_ROUND_TRIP_TIME_get();
  public final static int ENET_PEER_DEFAULT_PACKET_THROTTLE = enetJNI.ENET_PEER_DEFAULT_PACKET_THROTTLE_get();
  public final static int ENET_PEER_PACKET_THROTTLE_SCALE = enetJNI.ENET_PEER_PACKET_THROTTLE_SCALE_get();
  public final static int ENET_PEER_PACKET_THROTTLE_COUNTER = enetJNI.ENET_PEER_PACKET_THROTTLE_COUNTER_get();
  public final static int ENET_PEER_PACKET_THROTTLE_ACCELERATION = enetJNI.ENET_PEER_PACKET_THROTTLE_ACCELERATION_get();
  public final static int ENET_PEER_PACKET_THROTTLE_DECELERATION = enetJNI.ENET_PEER_PACKET_THROTTLE_DECELERATION_get();
  public final static int ENET_PEER_PACKET_THROTTLE_INTERVAL = enetJNI.ENET_PEER_PACKET_THROTTLE_INTERVAL_get();
  public final static int ENET_PEER_PACKET_LOSS_SCALE = enetJNI.ENET_PEER_PACKET_LOSS_SCALE_get();
  public final static int ENET_PEER_PACKET_LOSS_INTERVAL = enetJNI.ENET_PEER_PACKET_LOSS_INTERVAL_get();
  public final static int ENET_PEER_WINDOW_SIZE_SCALE = enetJNI.ENET_PEER_WINDOW_SIZE_SCALE_get();
  public final static int ENET_PEER_TIMEOUT_LIMIT = enetJNI.ENET_PEER_TIMEOUT_LIMIT_get();
  public final static int ENET_PEER_TIMEOUT_MINIMUM = enetJNI.ENET_PEER_TIMEOUT_MINIMUM_get();
  public final static int ENET_PEER_TIMEOUT_MAXIMUM = enetJNI.ENET_PEER_TIMEOUT_MAXIMUM_get();
  public final static int ENET_PEER_PING_INTERVAL = enetJNI.ENET_PEER_PING_INTERVAL_get();
  public final static int ENET_PEER_UNSEQUENCED_WINDOWS = enetJNI.ENET_PEER_UNSEQUENCED_WINDOWS_get();
  public final static int ENET_PEER_UNSEQUENCED_WINDOW_SIZE = enetJNI.ENET_PEER_UNSEQUENCED_WINDOW_SIZE_get();
  public final static int ENET_PEER_FREE_UNSEQUENCED_WINDOWS = enetJNI.ENET_PEER_FREE_UNSEQUENCED_WINDOWS_get();
  public final static int ENET_PEER_RELIABLE_WINDOWS = enetJNI.ENET_PEER_RELIABLE_WINDOWS_get();
  public final static int ENET_PEER_RELIABLE_WINDOW_SIZE = enetJNI.ENET_PEER_RELIABLE_WINDOW_SIZE_get();
  public final static int ENET_PEER_FREE_RELIABLE_WINDOWS = enetJNI.ENET_PEER_FREE_RELIABLE_WINDOWS_get();

  public final static int ENET_TIME_OVERFLOW = enetJNI.ENET_TIME_OVERFLOW_get();
}
