/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ENetJava;

public class ENetProtocolAcknowledge {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetProtocolAcknowledge(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetProtocolAcknowledge obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetProtocolAcknowledge(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeader(ENetProtocolCommandHeader value) {
    enetJNI.ENetProtocolAcknowledge_header_set(swigCPtr, this, ENetProtocolCommandHeader.getCPtr(value), value);
  }

  public ENetProtocolCommandHeader getHeader() {
    long cPtr = enetJNI.ENetProtocolAcknowledge_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocolCommandHeader(cPtr, false);
  }

  public void setReceivedReliableSequenceNumber(int value) {
    enetJNI.ENetProtocolAcknowledge_receivedReliableSequenceNumber_set(swigCPtr, this, value);
  }

  public int getReceivedReliableSequenceNumber() {
    return enetJNI.ENetProtocolAcknowledge_receivedReliableSequenceNumber_get(swigCPtr, this);
  }

  public void setReceivedSentTime(int value) {
    enetJNI.ENetProtocolAcknowledge_receivedSentTime_set(swigCPtr, this, value);
  }

  public int getReceivedSentTime() {
    return enetJNI.ENetProtocolAcknowledge_receivedSentTime_get(swigCPtr, this);
  }

  public ENetProtocolAcknowledge() {
    this(enetJNI.new_ENetProtocolAcknowledge(), true);
  }

}
