/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ENetJava;

public class ENetOutgoingCommand {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetOutgoingCommand(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetOutgoingCommand obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetOutgoingCommand(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOutgoingCommandList(ENetListNode value) {
    enetJNI.ENetOutgoingCommand_outgoingCommandList_set(swigCPtr, this, ENetListNode.getCPtr(value), value);
  }

  public ENetListNode getOutgoingCommandList() {
    long cPtr = enetJNI.ENetOutgoingCommand_outgoingCommandList_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetListNode(cPtr, false);
  }

  public void setReliableSequenceNumber(int value) {
    enetJNI.ENetOutgoingCommand_reliableSequenceNumber_set(swigCPtr, this, value);
  }

  public int getReliableSequenceNumber() {
    return enetJNI.ENetOutgoingCommand_reliableSequenceNumber_get(swigCPtr, this);
  }

  public void setUnreliableSequenceNumber(int value) {
    enetJNI.ENetOutgoingCommand_unreliableSequenceNumber_set(swigCPtr, this, value);
  }

  public int getUnreliableSequenceNumber() {
    return enetJNI.ENetOutgoingCommand_unreliableSequenceNumber_get(swigCPtr, this);
  }

  public void setSentTime(long value) {
    enetJNI.ENetOutgoingCommand_sentTime_set(swigCPtr, this, value);
  }

  public long getSentTime() {
    return enetJNI.ENetOutgoingCommand_sentTime_get(swigCPtr, this);
  }

  public void setRoundTripTimeout(long value) {
    enetJNI.ENetOutgoingCommand_roundTripTimeout_set(swigCPtr, this, value);
  }

  public long getRoundTripTimeout() {
    return enetJNI.ENetOutgoingCommand_roundTripTimeout_get(swigCPtr, this);
  }

  public void setRoundTripTimeoutLimit(long value) {
    enetJNI.ENetOutgoingCommand_roundTripTimeoutLimit_set(swigCPtr, this, value);
  }

  public long getRoundTripTimeoutLimit() {
    return enetJNI.ENetOutgoingCommand_roundTripTimeoutLimit_get(swigCPtr, this);
  }

  public void setFragmentOffset(long value) {
    enetJNI.ENetOutgoingCommand_fragmentOffset_set(swigCPtr, this, value);
  }

  public long getFragmentOffset() {
    return enetJNI.ENetOutgoingCommand_fragmentOffset_get(swigCPtr, this);
  }

  public void setFragmentLength(int value) {
    enetJNI.ENetOutgoingCommand_fragmentLength_set(swigCPtr, this, value);
  }

  public int getFragmentLength() {
    return enetJNI.ENetOutgoingCommand_fragmentLength_get(swigCPtr, this);
  }

  public void setSendAttempts(int value) {
    enetJNI.ENetOutgoingCommand_sendAttempts_set(swigCPtr, this, value);
  }

  public int getSendAttempts() {
    return enetJNI.ENetOutgoingCommand_sendAttempts_get(swigCPtr, this);
  }

  public void setCommand(ENetProtocol value) {
    enetJNI.ENetOutgoingCommand_command_set(swigCPtr, this, ENetProtocol.getCPtr(value), value);
  }

  public ENetProtocol getCommand() {
    long cPtr = enetJNI.ENetOutgoingCommand_command_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetProtocol(cPtr, false);
  }

  public void setPacket(ENetPacket value) {
    enetJNI.ENetOutgoingCommand_packet_set(swigCPtr, this, ENetPacket.getCPtr(value), value);
  }

  public ENetPacket getPacket() {
    long cPtr = enetJNI.ENetOutgoingCommand_packet_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ENetPacket(cPtr, false);
  }

  public ENetOutgoingCommand() {
    this(enetJNI.new_ENetOutgoingCommand(), true);
  }

}
