/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ENetJava;

public class ENetPacket {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetPacket(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetPacket obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetPacket(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setReferenceCount(long value) {
    enetJNI.ENetPacket_referenceCount_set(swigCPtr, this, value);
  }

  public long getReferenceCount() {
    return enetJNI.ENetPacket_referenceCount_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    enetJNI.ENetPacket_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return enetJNI.ENetPacket_flags_get(swigCPtr, this);
  }

  public void setData(SWIGTYPE_p_unsigned_char value) {
    enetJNI.ENetPacket_data_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getData() {
    long cPtr = enetJNI.ENetPacket_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setDataLength(long value) {
    enetJNI.ENetPacket_dataLength_set(swigCPtr, this, value);
  }

  public long getDataLength() {
    return enetJNI.ENetPacket_dataLength_get(swigCPtr, this);
  }

  public void setFreeCallback(SWIGTYPE_p_f_p_struct__ENetPacket__void value) {
    enetJNI.ENetPacket_freeCallback_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__ENetPacket__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__ENetPacket__void getFreeCallback() {
    long cPtr = enetJNI.ENetPacket_freeCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__ENetPacket__void(cPtr, false);
  }

  public void setUserData(SWIGTYPE_p_void value) {
    enetJNI.ENetPacket_userData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserData() {
    long cPtr = enetJNI.ENetPacket_userData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public ENetPacket() {
    this(enetJNI.new_ENetPacket(), true);
  }

}
