/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ENetJava;

public class ENetProtocolHeader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ENetProtocolHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ENetProtocolHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        enetJNI.delete_ENetProtocolHeader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPeerID(int value) {
    enetJNI.ENetProtocolHeader_peerID_set(swigCPtr, this, value);
  }

  public int getPeerID() {
    return enetJNI.ENetProtocolHeader_peerID_get(swigCPtr, this);
  }

  public void setSentTime(int value) {
    enetJNI.ENetProtocolHeader_sentTime_set(swigCPtr, this, value);
  }

  public int getSentTime() {
    return enetJNI.ENetProtocolHeader_sentTime_get(swigCPtr, this);
  }

  public ENetProtocolHeader() {
    this(enetJNI.new_ENetProtocolHeader(), true);
  }

}
