/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ENetJava;

public class SWIGTYPE_p_f_p_void_p_q_const__ENetBuffer_size_t_size_t_p_unsigned_char_size_t__size_t {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p_void_p_q_const__ENetBuffer_size_t_size_t_p_unsigned_char_size_t__size_t(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_void_p_q_const__ENetBuffer_size_t_size_t_p_unsigned_char_size_t__size_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_void_p_q_const__ENetBuffer_size_t_size_t_p_unsigned_char_size_t__size_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

